### ISSUE TITLE
Vk message send

### ISSUE THREAD

**Issue by Dronax** [andrey-helldar/vk#17]
Hello, How I can send message? Method: messages.send

**Comment by andrey-helldar** [comment]
Hello!
Unfortunately, at the moment I have not transferred all the VK API methods ([available methods] (https://github.com/andrey-helldar/vk#available-methods))

But you can send PR to their addition.
Example: https://github.com/andrey-helldar/vk/blob/master/src/Facade/Apps.php

**Comment by Dronax** [comment]
What is this "PR" ? How I can add method "messages.send" ?

**Comment by andrey-helldar** [comment]
PR it's a [pull requests](https://github.com/andrey-helldar/vk/pulls)

**Comment by Dronax** [comment]
I created PR with Messages.

**Comment by andrey-helldar** [comment]
In the near future I will check the work of the method #18 and add it to the package.

**Comment by andrey-helldar** [comment]
Method added.
