### ISSUE TITLE
Vk api with group bots

### ISSUE THREAD

**Issue by Dronax** [andrey-helldar/vk#20]
Hello, I have group in vk. And have chat bot. I have token group, how I can write this token in config if I have and token user and token group?  Link: https://vk.com/dev/bots_docs

**Comment by andrey-helldar** [comment]
Hi! The current version of the package does not yet know how to work with bots. At the moment, the package only supports some VK API methods version 5.63 and below.

**Comment by Dronax** [comment]
Andrey, Vk bots use vk api, but how I can add access_token? If I already have access_token user.

**Comment by andrey-helldar** [comment]
Use [auth button](https://github.com/andrey-helldar/vk/blob/master/README.md#template)for the authorization

When authorizing the VK API, the local account ID retains the account identifier on the site and the VK system identifier in the local table. Both fields must be unique in the table. This means that, at the moment, only [one access_token](https://github.com/andrey-helldar/vk/blob/master/src/Controllers/AuthController.php#L77) can be obtained from [one authorized user](https://github.com/andrey-helldar/vk/blob/master/src/Database/migrations/2017_03_28_000000_create_vk_users_table.php#L21).
