### ISSUE TITLE
php artisan migrate  : SQLSTATE[42000]: Syntax error or access violation

### ISSUE THREAD

**Issue by almohajire** [andrey-helldar/vk#23]
c:\xampp\htdocs\laravel>php artisan migrate

   Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null, `response` json null, `created_at` timestamp null, `updated_at` times' at line 1 (SQL: create table `vk_requests` (`id` int unsigned not null auto_increment primary key, `user_id` int null, `method` varchar(191) not null, `request` json null, `response` json null, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

  at C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'json null, `response` json null, `created_at` timestamp null, `updated_at` times' at line 1")
      C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Connection.php:452

  2   PDO::prepare("create table `vk_requests` (`id` int unsigned not null auto_increment primary key, `user_id` int null, `method` varchar(191) not null, `request` json null, `response` json null, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'")
      C:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Database\Connection.php:452

  Please use the argument -v to see more details.

**Comment by mrhili** [comment]
Install him and then

php artisan vendor:publish

then migrate

**Comment by andrey-helldar** [comment]
What version of MariaDB are you using? The project uses the json field type in migrations. MariaDB has introduced support for this type of field since version 10.2.3.
https://mariadb.com/kb/en/library/json-functions/

**Comment by almohajire** [comment]
![untitledmaria](https://user-images.githubusercontent.com/28836771/43974736-5b1c9692-9cd3-11e8-9f4e-6b10ed48db8c.jpg)

**Comment by andrey-helldar** [comment]
@almohajire MariaDB 10.1.34 version is not supported JSON field types.

This package using `json` field types ([this](https://github.com/andrey-helldar/vk/blob/master/src/Database/migrations/2017_03_28_000000_create_vk_requests_table.php#L23-L24) and [this](https://github.com/andrey-helldar/vk/blob/master/src/Database/migrations/2017_03_28_000000_create_vk_users_table.php#L24))

> JSON is fast becoming the standard format for data interchange and for unstructured data, and MariaDB 10.2 adds a range on JSON supporting functions, even though a JSON datatype isn't implemented yet. There are some reasons why there isn't a JSON datatype, but one is that there are actually not that many advantages to that as JSON is a text-based format. This blog post aims to describe JSON and the use cases for it, as well as to describe the MariaDB 10.2 JSON functions and uses for these, as well as showing some other additions to MariaDB 10.2 that are useful for JSON processing.

https://mariadb.com/resources/blog/json-mariadb-102

**Comment by almohajire** [comment]
ok tnx 
Update xampp from maria db 10.1 to 10.2
https://stackoverflow.com/questions/44027926/update-xampp-from-maria-db-10-1-to-10-2
now it's working
