### ISSUE TITLE
Class 'Helldar\Vk\VkServiceProvider' not found

### ISSUE THREAD

**Issue by mrhili** [andrey-helldar/vk#24]
![image](https://user-images.githubusercontent.com/40344789/43934077-b8cc1e88-9c4d-11e8-8ac2-5b83a8907165.png)

**Comment by mrhili** [comment]
![image](https://user-images.githubusercontent.com/40344789/43934198-59c1ca4a-9c4e-11e8-8cfa-e007dfa9a0f8.png)

Without registring

**Comment by andrey-helldar** [comment]
`Open up config/app.php and add the following to the providers key, or if you're using Laravel 5.5, this can be done via the automatic package discovery.`

And execute command `composer dumpauto`.
